version: "3.9"

services:
  db:
    image: postgres:16
    container_name: gesture-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gesture
    ports:
      - "5434:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: animal-gesture-api:latest
    container_name: animal-gesture-api
    depends_on:
      - db
      - ml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gesture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      ML_BASE_URL: http://ml:8000
    ports:
      - "8080:8080"
    networks:
      - backend

  ml:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    image: animal-gesture-ml:latest
    container_name: animal-gesture-ml
    ports:
      - "8000:8000"
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
